### ISSUE TITLE
Look at the task carefully

### ISSUE THREAD

**Issue by ChernitsinNikolay** [PavelChernicyn/Drilling#4]
> Дан набор из N целых положительных чисел. Необходимо определить, с какой цифры чаще всего начинается десятичная запись чисел этого набора. Если таких цифр несколько, необходимо вывести наибольшую из них.

https://github.com/PavelChernicyn/Drilling/blob/92b66f0db0d74bdaaecedfddd7698419a4295cd6/FindTheNumbers.cpp#L30

Недоделано

**Comment by PavelChernicyn** [comment]
А что именно не доделано? У меня там массив из десяти переменных (0-9), в нем считаю кол-во чисел начинающихся с определенной цифры. Потом ищу в этом массиве МАХ или равно МАХ и вывожу

**Comment by ChernitsinNikolay** [comment]
Да, я неправильно задание прочитал
