### ISSUE TITLE
Optimization

### ISSUE THREAD

**Issue by ChernitsinNikolay** [PavelChernicyn/Drilling#5]
https://github.com/PavelChernicyn/Drilling/blob/452e462d3b0d74cc35b1c59ddac4f1f55428b927/FindTheNumbers.cpp#L24-L29
Можно выкинуть переменную max

**Comment by PavelChernicyn** [comment]
int c=0;
	for (int i=1; i<p; ++i){
		if(mas[i]>=mas[c]) c=i;
	}
	cout << c;
